# Generated by Django 5.0.1 on 2026-02-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodosTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('todayTarget', models.BooleanField(default=True)),
                ('timeNeeded', models.PositiveBigIntegerField(help_text='Time Needed in Minutes')),
                ('priority', models.PositiveSmallIntegerField(default=5, help_text='1(low)->to->10(high)')),
                ('postedTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
